artifacts_root: artifacts               # main artifact folder 

data_ingestion: 
 root_dir: artifacts/data_ingestion    # folder for data ingestion step
 source_url: https://github.com/mayurkadam9833/Datasets/raw/refs/heads/main/health_data.zip  # source url for download data
 local_data_file: artifacts/data_ingestion/health_data.zip   # downloaded file path
 unzip_dir: artifacts/data_ingestion                         # unzip dataset path

data_validation: 
 root_dir: artifacts/data_validation        # folder for data validation step           
 unzip_data_path: artifacts/data_ingestion/health_data.csv  # unzip data path
 validation: artifacts/data_validation/status_file.txt      # valdiation file path

data_transformation: 
 root_dir: artifacts/data_transformation               # folder for data transformation step
 data_file: artifacts/data_ingestion/health_data.csv   # dataset path   

model_trainer: 
 root_dir: artifacts/model_trainer                          # folder for model trainer step
 train_data_path: artifacts/data_transformation/train.csv   # train data path
 model_name: artifacts/model_trainer/model.joblib           # trained model path

model_evaluation: 
 root_dir: artifacts/model_evaluation                       # folder for model trainer step
 test_data_path: artifacts/data_transformation/test.csv     # test data path
 model_path: artifacts/model_trainer/model.joblib           # trained model path    
 evaluation: artifacts/model_evaluation/metrics.json        # evaluation metrics

